# Generated by Django 5.2.6 on 2026-04-20 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteGlobal',
            fields=[
                ('clave', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('valor', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Ajustes Globales',
            },
        ),
        migrations.CreateModel(
            name='ReduccionHijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.IntegerField(default=0)),
                ('m_in', models.TimeField(default='08:00')),
                ('m_out', models.TimeField(default='14:00')),
                ('t_in', models.TimeField(blank=True, null=True)),
                ('t_out', models.TimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reduccion_jornada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDefecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=15)),
                ('m_in', models.TimeField(blank=True, null=True)),
                ('m_out', models.TimeField(blank=True, null=True)),
                ('t_in', models.TimeField(blank=True, null=True)),
                ('t_out', models.TimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_defecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'dia')},
            },
        ),
        migrations.CreateModel(
            name='PeriodoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('inicio', models.CharField(max_length=5)),
                ('fin', models.CharField(max_length=5)),
                ('h_sem', models.FloatField(default=37.5)),
                ('h_tarde', models.FloatField(default=0.0)),
                ('es_estricto', models.BooleanField(default=True)),
                ('m_in', models.TimeField(blank=True, null=True)),
                ('m_out', models.TimeField(blank=True, null=True)),
                ('t_in', models.TimeField(blank=True, null=True)),
                ('t_out', models.TimeField(blank=True, null=True)),
                ('usa_tarde', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_especiales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('m_in', models.TimeField(blank=True, null=True)),
                ('m_out', models.TimeField(blank=True, null=True)),
                ('t_in', models.TimeField(blank=True, null=True)),
                ('t_out', models.TimeField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
