# Generated by Django 6.0.3 on 2026-03-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteGlobal',
            fields=[
                ('clave', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('valor', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Ajustes Globales',
            },
        ),
        migrations.CreateModel(
            name='HorarioDefecto',
            fields=[
                ('dia', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('m_in', models.TimeField(blank=True, null=True)),
                ('m_out', models.TimeField(blank=True, null=True)),
                ('t_in', models.TimeField(blank=True, null=True)),
                ('t_out', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoEspecial',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('inicio', models.CharField(max_length=5)),
                ('fin', models.CharField(max_length=5)),
                ('h_sem', models.FloatField(default=37.5)),
                ('h_tarde', models.FloatField(default=0.0)),
                ('es_estricto', models.BooleanField(default=True)),
                ('m_in', models.TimeField(blank=True, null=True)),
                ('m_out', models.TimeField(blank=True, null=True)),
                ('t_in', models.TimeField(blank=True, null=True)),
                ('t_out', models.TimeField(blank=True, null=True)),
                ('usa_tarde', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReduccionHijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.IntegerField(default=0)),
                ('m_in', models.TimeField(default='08:00')),
                ('m_out', models.TimeField(default='14:00')),
                ('t_in', models.TimeField(blank=True, null=True)),
                ('t_out', models.TimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('m_in', models.TimeField(blank=True, null=True)),
                ('m_out', models.TimeField(blank=True, null=True)),
                ('t_in', models.TimeField(blank=True, null=True)),
                ('t_out', models.TimeField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
