# Generated by Django 5.2.6 on 2026-04-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiario',
            name='es_periodo_especial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='es_teletrabajo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='horas_m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='horas_t',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='ReduccionHijos',
        ),
    ]
