# Generated by Django 5.2.6 on 2026-04-20 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_jornada', models.CharField(choices=[('FIJO', 'Horario Fijo'), ('FLEXIBLE', 'Horario Flexible')], default='FLEXIBLE', max_length=10)),
                ('horas_semanales_estandar', models.FloatField(default=37.5)),
                ('margen_entrada', models.IntegerField(default=15, help_text='Minutos de cortesía')),
                ('obligatoriedad_tarde', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_principal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('horas_semanales', models.FloatField(default=35.0)),
                ('es_intensiva', models.BooleanField(default=False)),
                ('m_in', models.TimeField(blank=True, null=True)),
                ('m_out', models.TimeField(blank=True, null=True)),
                ('t_in', models.TimeField(blank=True, null=True)),
                ('t_out', models.TimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Horarios Especiales',
            },
        ),
    ]
