# Generated by Django 5.2.6 on 2026-04-20 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionhorario',
            name='margen_entrada',
        ),
        migrations.RemoveField(
            model_name='configuracionhorario',
            name='obligatoriedad_tarde',
        ),
        migrations.AddField(
            model_name='configuracionhorario',
            name='descanso_min_comida',
            field=models.IntegerField(default=30, help_text='Minutos mínimos entre salida M y entrada T'),
        ),
        migrations.AddField(
            model_name='configuracionhorario',
            name='dias_permitidos_tarde',
            field=models.CharField(default='1,2,3,4', help_text='IDs de días (1=Lunes...) separated por comas', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionhorario',
            name='max_hora_tarde',
            field=models.TimeField(default='20:00', help_text='Hora máxima hasta la que cuenta la tarde'),
        ),
        migrations.AddField(
            model_name='configuracionhorario',
            name='min_horas_tarde',
            field=models.FloatField(default=1.0, help_text='Mínimo de horas a realizar si se hace tarde'),
        ),
        migrations.AlterField(
            model_name='configuracionhorario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_horario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HorarioDefecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('m_in', models.TimeField(blank=True, null=True)),
                ('m_out', models.TimeField(blank=True, null=True)),
                ('t_in', models.TimeField(blank=True, null=True)),
                ('t_out', models.TimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_base', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia_semana'],
                'unique_together': {('usuario', 'dia_semana')},
            },
        ),
        migrations.DeleteModel(
            name='HorarioEspecial',
        ),
    ]
