# Generated by Django 5.2.6 on 2026-04-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0002_remove_configuracionhorario_margen_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionhorario',
            name='dias_obligatorios_tarde',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionhorario',
            name='min_dias_tarde',
            field=models.IntegerField(default=1, help_text='Mínimo de tardes a realizar por semana'),
        ),
        migrations.AlterField(
            model_name='configuracionhorario',
            name='descanso_min_comida',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='configuracionhorario',
            name='dias_permitidos_tarde',
            field=models.CharField(default='1,2,3,4', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracionhorario',
            name='max_hora_tarde',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AlterField(
            model_name='configuracionhorario',
            name='min_horas_tarde',
            field=models.FloatField(default=1.0),
        ),
    ]
