# Generated by Django 5.2.6 on 2026-04-20 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0003_configuracionhorario_dias_obligatorios_tarde_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracionhorario',
            old_name='descanso_min_comida',
            new_name='minutos_descanso',
        ),
        migrations.RemoveField(
            model_name='configuracionhorario',
            name='dias_permitidos_tarde',
        ),
        migrations.RemoveField(
            model_name='configuracionhorario',
            name='min_dias_tarde',
        ),
        migrations.AddField(
            model_name='configuracionhorario',
            name='dias_teletrabajo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionhorario',
            name='max_hora_manana',
            field=models.TimeField(default='15:00'),
        ),
        migrations.AddField(
            model_name='configuracionhorario',
            name='max_horas_manana_presencial',
            field=models.FloatField(default=6.0),
        ),
        migrations.AddField(
            model_name='configuracionhorario',
            name='max_horas_manana_teletrabajo',
            field=models.FloatField(default=7.0),
        ),
        migrations.CreateModel(
            name='HorarioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('horas_semanales', models.FloatField(default=35.0)),
                ('es_intensiva', models.BooleanField(default=False)),
                ('m_in', models.TimeField(blank=True, null=True)),
                ('m_out', models.TimeField(blank=True, null=True)),
                ('t_in', models.TimeField(blank=True, null=True)),
                ('t_out', models.TimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Horarios Especiales',
            },
        ),
    ]
