# Generated by Django 5.2.6 on 2026-04-20 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0004_rename_descanso_min_comida_configuracionhorario_minutos_descanso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioespecial',
            name='es_intensiva',
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='dias_obligatorios_tarde',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='dias_teletrabajo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='horarioespecial',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_especiales', to=settings.AUTH_USER_MODEL),
        ),
    ]
