# Generated by Django 5.2.6 on 2026-04-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0005_remove_horarioespecial_es_intensiva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioespecial',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='horarioespecial',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='dia_fin',
            field=models.IntegerField(default=31),
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='dia_inicio',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='max_hora_manana',
            field=models.TimeField(default='15:00'),
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='max_hora_tarde',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='mes_fin',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='mes_inicio',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='min_horas_tarde',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='minutos_descanso',
            field=models.IntegerField(default=30),
        ),
    ]
