# Generated by Django 5.2.6 on 2026-04-20 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0006_remove_horarioespecial_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioespecial',
            name='m_in',
        ),
        migrations.RemoveField(
            model_name='horarioespecial',
            name='m_out',
        ),
        migrations.RemoveField(
            model_name='horarioespecial',
            name='t_in',
        ),
        migrations.RemoveField(
            model_name='horarioespecial',
            name='t_out',
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='max_presencial',
            field=models.FloatField(default=6.0),
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='max_teletrabajo',
            field=models.FloatField(default=7.0),
        ),
        migrations.CreateModel(
            name='DiaHorarioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField()),
                ('m_in', models.TimeField(blank=True, null=True)),
                ('m_out', models.TimeField(blank=True, null=True)),
                ('t_in', models.TimeField(blank=True, null=True)),
                ('t_out', models.TimeField(blank=True, null=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_dias', to='opciones.horarioespecial')),
            ],
            options={
                'unique_together': {('periodo', 'dia_semana')},
            },
        ),
    ]
