# Generated by Django 5.2.6 on 2026-04-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0007_remove_horarioespecial_m_in_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diahorarioespecial',
            options={'ordering': ['dia_semana']},
        ),
        migrations.AlterModelOptions(
            name='horarioespecial',
            options={},
        ),
        migrations.AlterField(
            model_name='diahorarioespecial',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')]),
        ),
    ]
