# Generated by Django 5.2.6 on 2026-04-20 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0008_alter_diahorarioespecial_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoDias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2026)),
                ('vacaciones_totales', models.IntegerField(default=22)),
                ('asuntos_propios_totales', models.IntegerField(default=6)),
                ('vacaciones_disfrutadas', models.IntegerField(default=0)),
                ('asuntos_disfrutados', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saldo de Días',
                'unique_together': {('usuario', 'anio')},
            },
        ),
    ]
