# Generated by Django 5.2.6 on 2026-04-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0009_saldodias'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionhorario',
            name='max_horas_tarde',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='max_horas_tarde',
            field=models.FloatField(default=3.0),
        ),
    ]
