# Generated by Django 5.2.6 on 2026-04-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0010_configuracionhorario_max_horas_tarde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionhorario',
            name='hora_inicio_conteo',
            field=models.TimeField(default='07:30'),
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='hora_inicio_conteo',
            field=models.TimeField(default='07:30'),
        ),
    ]
