# Generated by Django 5.2.6 on 2026-04-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0011_configuracionhorario_hora_inicio_conteo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionhorario',
            name='oblig_manana_in',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='configuracionhorario',
            name='oblig_manana_out',
            field=models.TimeField(default='14:30'),
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='oblig_manana_in',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='oblig_manana_out',
            field=models.TimeField(default='14:30'),
        ),
    ]
