# Generated by Django 5.2.6 on 2026-04-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0012_configuracionhorario_oblig_manana_in_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saldodias',
            options={'verbose_name': 'Saldo de Días', 'verbose_name_plural': 'Saldos de Días'},
        ),
    ]
