# Generated by Django 5.2.6 on 2026-04-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0013_alter_saldodias_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionhorario',
            name='horas_festivo',
            field=models.FloatField(default=7.5),
        ),
        migrations.AddField(
            model_name='horarioespecial',
            name='horas_festivo',
            field=models.FloatField(default=7.5),
        ),
    ]
