# Generated by Django 5.2.6 on 2026-04-25 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0015_festivoespecial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FestivoEspecial',
        ),
    ]
