# Generated by Django 5.2.6 on 2026-04-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0017_festivoespecial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldodias',
            old_name='vacaciones_disfrutadas',
            new_name='enfermedad_sin_justificar_disfrutados',
        ),
        migrations.RemoveField(
            model_name='saldodias',
            name='vacaciones_totales',
        ),
        migrations.AddField(
            model_name='saldodias',
            name='enfermedad_sin_justificar_totales',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='saldodias',
            name='vacaciones_bloques_disfrutadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saldodias',
            name='vacaciones_bloques_totales',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='saldodias',
            name='vacaciones_libres_disfrutadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saldodias',
            name='vacaciones_libres_totales',
            field=models.IntegerField(default=4),
        ),
    ]
