# Generated by Django 5.2.12 on 2026-03-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('tipo', models.CharField(choices=[('FESTIVO', 'Festivo'), ('VACACIONES', 'Vacaciones'), ('SIN_SUELDO', 'Día sin Sueldo'), ('BAJA', 'Baja Médica'), ('OTRO', 'Otro')], default='FESTIVO', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Evento de Calendario',
                'verbose_name_plural': 'Eventos de Calendario',
            },
        ),
    ]
