# Generated by Django 5.2.6 on 2026-04-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocalendario',
            name='tipo',
            field=models.CharField(choices=[('FESTIVO', 'Festivo Extra'), ('VACACIONES', 'Vacaciones'), ('ASUNTOS_PROPIOS', 'Asuntos Propios'), ('BAJA', 'Baja Médica'), ('ENFERMEDAD', 'Enfermedad Puntual'), ('SIN_SUELDO', 'Día sin Sueldo'), ('OTRO', 'Otro')], default='FESTIVO', max_length=20),
        ),
    ]
